# fly.toml app configuration file generated for astrbot-z on 2025-04-25T21:54:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'astrbot-z'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 6185
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  internal_port = 6195
  protocol = "tcp"
  [[services.ports]]
    port = 6195

[[services]]
  internal_port = 6199
  protocol = "tcp"
  [[services.ports]]
    port = 6199

[[mounts]]
  source      = "astrbot_db"
  destination = "/AstrBot/data"